### ISSUE TITLE
Array and string offset access syntax with curly braces is deprecated

### ISSUE THREAD

**Issue by alamgircsejnu** [milon/barcode#98] opened 2020-01-24 09:53 UTC
I am getting this error mesage when I am trying to get png barcode of type  C128 .

Here is the screenshot of the issue.

![Screenshot (45)](https://user-images.githubusercontent.com/19221035/73060293-b5ec6480-3ec1-11ea-9f3b-03534cef13c9.png)

**Comment by 760524mkfa00** [comment] 2020-02-04 06:59
I had to change all the curly braces in the file to get it working again.

**Comment by 760524mkfa00** [comment] 2020-02-04 07:09
```

$code{0};
```
you will need to go through the file and change all occurrences where there is curly braces to square braces:

```
$code[0];
```
The file below I have already done this.
[DNS1D.txt](https://github.com/milon/barcode/files/4151835/DNS1D.txt)

**Comment by twf-nikhila** [comment] 2020-02-11 13:48
Getting the same error. 

Array and string offset access syntax with curly braces is deprecated

vendor/milon/barcode/src/Milon/Barcode/DNS1D.phpLine:560

So the curly braces here is deprecated and needs to be changed to tuple format.
Reference: https://wiki.php.net/rfc/deprecate_curly_braces_array_access

**Comment by neilcrookes** [comment] 2020-03-04 18:40
Duplicate of #94

Fixed by https://github.com/milon/barcode/pull/92

Looks like @milon just needs to tag a release with these changes in as requested by @daaner https://github.com/milon/barcode/pull/92#issuecomment-573281213

Could you do that please @milon, then you could close this and #94

**Comment by milon** [comment] 2020-03-05 12:13
I already added a new tag. please use that.

**Closed by milon** 2020-03-05 12:13 UTC

**Comment by mnazmi23** [comment] 2020-04-06 10:10
Hi, how do I use this fix using the release 6.0. I am currently using laravel 6.18 and the error are only fixed when I use the dev-master version and if possible I would like to avoid that. I wamt to use the version that works with my laravel version, but with this fixes. Installing 7.0 version was unsuccessful of course.

Thank you.

**Comment by tfevan** [comment] 2020-10-22 09:35
Easy fix,
After upgrade to PHP 7.4 I am getting this error.
To fix this issue then replace  **vendor/milon/barcode/src/Milon/Barcode/DNS1D.php** file with **[DNS1D.php](https://github.com/milon/barcode/files/4151835/DNS1D.txt)**
